#
# For Cloud Team 63:
#  * Akshaya Shankar - 1058281
#  * Andy Phan - 696382
#  * Chenbang Huang - 967186
#  * Prashanth Shrinivasan - 986472
#  * Qian Sun – 1027266
#

- name: Start batching.
  include_role:
    name: os-create-instance
  vars:
    instance_name: "{{ instance.name + '-' + batch_var|string }}"
  with_sequence: start=1 end={{ instance.amount }}
  loop_control:
    loop_var: batch_var