- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    # prereq
    - role: os-common
    #- role: os-find-images
    # prepare for instance creation
    - role: os-create-volumes
    - role: os-create-security-groups
    # now create instances
    - role: os-create-instance
    #- role: os-create-volume-snapshots
  post_tasks:
    - name: Select random node to be "CouchDB's setup master".
      set_fact:
        couchdb_node_leader: "{{ item }}"
      with_random_choice: "{{ groups['db'] }}"

    - name: Select random manager node to init swarm.
      set_fact:
        docker_swarm_leader: "{{ item }}"
      with_random_choice: "{{ groups['managers'] }}"
    
    # Credit to: https://stackoverflow.com/a/41455193 for random UUIDs.
    #couchdb_secret: "{{ 99999999 | random | to_uuid }}"
    #couchdb_cookie: "{{ 99999999 | random | to_uuid }}"

    - debug:
        msg: "{{ hostvars['localhost'] }}"

- hosts: all:!localhost
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  vars:
    jsonKeys: "{{ lookup('file', 'api_keys.json') | from_json }}"
  roles:
    - role: vm-set-proxy
      when: ansible_env.http_proxy is not defined
    - role: vm-mount-volumes
      vars:
        mounts:
          - device: "/dev/vdb"
            path: "{{ couchDB_mount_point }}"
    - role: vm-install-python
    - role: vm-install-docker
    #- role: vm-init-couchdb
    #- role: main-start-twitter-script
  tags:
    - setup_packages

- hosts: all:!localhost
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  vars:
    swarm_leader: "{{ hostvars['localhost']['docker_swarm_leader'] }}"
  roles:
    - role: docker-start-swarm

- hosts: db
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  vars:
    # Credit to: https://stackoverflow.com/a/36312618 for the code
    host_count: "{{ groups['db'] | length }}"
  roles:
    - role: db-setup-couchdb
    