- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    # prereq
    - role: os-common
    #- role: os-find-images
    # prepare for instance creation
    - role: os-create-volumes
    - role: os-create-security-groups
    # now create instances
    - role: os-create-instance
    #- role: os-create-volume-snapshots

- hosts: all:!localhost
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  vars:
    couchDB_mount_point: "./couchDB_Data"
    jsonKeys: "{{ lookup('file', 'api_keys.json') | from_json }}"
  roles:
    - role: vm-set-proxy
      when: ansible_env.http_proxy is not defined
    - role: vm-mount-volumes
      vars:
        mounts:
          - device: "/dev/vdb"
            path: "{{ couchDB_mount_point }}"
    - role: vm-install-python
    - role: vm-install-docker
    #- role: vm-init-couchdb
    #- role: main-start-twitter-script