#
# For Cloud Team 63:
#  * Akshaya Shankar - 1058281
#  * Andy Phan - 696382
#  * Chenbang Huang - 967186
#  * Prashanth Shrinivasan - 986472
#  * Qian Sun – 1027266
#

- name: Copy Docker compose file to start containers.
  copy:
    src: "docker-compose.yml"
    dest: "./docker-compose.yml"

- name: Start the Docker stack
  shell: "docker stack deploy -c docker-compose.yml test"