- debug:
    msg: "Hostname: {{ inventory_hostname }}"

- name: Add proxy names
  lineinfile:
    dest: '/etc/environment'
    line: '{{ item }}'
  with_items:
    - 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'