version: "3.3"

services:
  haproxy:
    image: "haproxy"
    ports:
      - "5700:5984"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

  twitscript:
    image: "127.0.0.1:4000/twittest"
    environment:
      - https_proxy=http://wwwproxy.unimelb.edu.au:8000
      - http_proxy=http://wwwproxy.unimelb.edu.au:8000
      - no_proxy=haproxy
      - DB_URL=http://user:pass@haproxy:5984/
      - DB_TASK_NUM={{.Task.Slot}}
      - ARCGIS_USERNAME=aphan1um
      - ARCGIS_PASS=andyphan1
      - GEO_RADIAL=-28.052919,133.652009,2160km
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: ~/shapes
        target: /twitter/shapes
    depends_on:
      - haproxy

  restapi:
    image: "127.0.0.1:4000/restapi"
    environment:
      - API_COUCHDB_URL=http://user:pass@haproxy:5984/
      - API_TWEETS_DBNAME=tweets_final
      - API_AURIN_DBNAME=aurin_lga
    volumes:
      - type: bind
        source: ~/shapes
        target: /restapi/shapes
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - haproxy
    
  website:
    image: "127.0.0.1:4000/web"
    ports:
      - "81:80"
    depends_on:
      - restapi

configs:
  haproxy_config:
    external: true
    