#
# For Cloud Team 63:
#  * Akshaya Shankar - 1058281
#  * Andy Phan - 696382
#  * Chenbang Huang - 967186
#  * Prashanth Shrinivasan - 986472
#  * Qian Sun – 1027266
#

- name: Format volumes
  filesystem:
    fstype: ext4
    dev: '{{ item.device }}'
    force: no
  loop: '{{ mounts }}'


- name: Mount volumes
  mount:
    path: '{{ item.path }}'
    src: '{{ item.device }}'
    fstype: ext4
    state: mounted
  loop: '{{ mounts }}'
  become: yes