version: '3.7'

services:
  couchdb:
    image: couchdb:2.3.0
    environment:
      COUCHDB_USER: user
      COUCHDB_PASSWORD: pass
      COUCHDB_SECRET: testcookie
      DB_IP_ADDR: {{.Node.Labels.nectar_ip}}
    ports:
      - target: 5984
        published: 5984
        mode: host
      - target: 9100
        published: 9100
        mode: host
      - target: 5986
        published: 5986
        mode: host
      - target: 4369
        published: 4369
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.db == yes
      mode: global
    command: "-setcookie monster -name couchdb@${{DB_IP_ADDR}}"
    volumes:
      - /home/ubuntu/couchDB_Data:/opt/couchdb/data