# Create volumes from vars
- name: Create volume(s) on NeCTAR
  os_volume:
    display_name: '{{ item.key }}'
    size: '{{ item.value.size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  with_dict: '{{ volumes }}'
  register: os_vol

# Credit to: https://stackoverflow.com/a/48825995 for the idea with
# merging dictionaries
- name: Create a list of volume IDs
  set_fact:
    volumes: "{{ volumes | combine(temp_dict, recursive=True) }}"
  # os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  vars:
    temp_dict: "{ '{{ item.item.key }}': { 'id': '{{ item.id }}' } }"
  loop: '{{ os_vol.results }}'

- debug:
    msg: "{{ volumes }}"