#
# For Cloud Team 63:
#  * Akshaya Shankar - 1058281
#  * Andy Phan - 696382
#  * Chenbang Huang - 967186
#  * Prashanth Shrinivasan - 986472
#  * Qian Sun – 1027266
#

- name: Install Python
  become: yes
  apt:
    name: ['python', 'python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"