- name: Copy HAProxy config file.
  copy:
    src: haproxy.cfg
    dest: ./haproxy.cfg

- name: Add DB instances to config file.
  lineinfile:
    path: ./haproxy.cfg
    line: "{{ add_text }}"
  vars:
    add_text: "{{ groups['db'] | map('regex_replace', '^(.*)$',
    '    server couchdb-\\1 \\1:5984 check inter 5s')
    | list | join('\n') }}"

- name: Prepare Docker config file
  block:
    - command: docker config rm haproxy_config
      ignore_errors: yes
    - command: docker config create haproxy_config haproxy.cfg

- name: Start HAProxy (reverse proxy + load balancer for CouchDB).
  shell: >
    docker service create --name haproxy-couchdb
    -p {{ ha_port_proxy }}:5984 --replicas={{ ha_replicas }}
    --config src=haproxy_config,target="/usr/local/etc/haproxy/haproxy.cfg"
    haproxy
  # TODO: Change this 5700:5984 to be a variable, magic number yuck