# Create a NecTAR instance

- name: Create instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instances
  loop: "{{ instances }}"

# TODO: Thanks to https://stackoverflow.com/a/41908853 for the idea
- name: Attach volumes
  os_server_volume:
    state: present
    server: "{{ item.0.name }}"
    volume: "{{ volumes[item.1].id }}"
  with_subelements:
    - "{{ instances }}"
    - volumes

- debug:
    msg: "Instance created. IP Address: {{ item.openstack.public_v4 }}"
  when: item.openstack is defined
  loop: "{{ os_instances.results }}"
  loop_control:
    label: "{{ item.openstack.name }}"

- name: Add created instances to inventory
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: "{{ item.item.group }}"
    ansible_ssh_host: '{{ item.openstack.public_v4 }}'
  loop: "{{ os_instances.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Preparation - Setting correct permissions for private key
  command: chmod 600 '{{ ansible_ssh_private_key_file }}'

  # Credit to: https://github.com/msolberg/openstack-ansible-demo/blob/master/tutorial/README.md
- name: Await SSH connection for each instance
  command: >
    ssh -i {{ ansible_ssh_private_key_file }}
    -oBatchMode=yes -oStrictHostKeyChecking=no
    ubuntu@{{ item.openstack.public_v4 }} true
  register: result
  until: result is success
  retries: 20
  delay: 15
  loop_control:
    label: "{{ item.item }}"
  loop: "{{ os_instances.results }}"

- pause:
    seconds: 20