version: "3.3"

services:
  haproxy:
    image: "haproxy"
    ports:
      - "5700:5984"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      net_db:
        aliases:
          - haproxy
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

  twitscript:
    image: "127.0.0.1:5000/twittest"
    environment:
      - https_proxy=http://wwwproxy.unimelb.edu.au:8000
      - http_proxy=http://wwwproxy.unimelb.edu.au:8000
      - no_proxy=haproxy
      - DB_URL=http://user:pass@haproxy:5984/
      - DB_TASK_NUM={{.Task.Slot}}
      - ARCGIS_USERNAME=aphan1um
      - ARCGIS_PASS=andyphan1
      - GEO_RADIAL=-28.052919,133.652009,2160km
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - net_db
    depends_on:
      - haproxy

configs:
  haproxy_config:
    external: true

networks:
  net_db:
    driver: overlay
    