- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    # prereq
    - role: openstack-common
    - role: find-images
    # prepare for instance creation
    - role: create-volumes
    - role: create-security-groups
    # now create instances
    - role: create-instance
    - role: create-volume-snapshots

- hosts: vms
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  vars:
    ansible_ssh_private_key_file: "./private_key_aphan1.pem"
  tasks:
    - debug:
        msg: "Hostname: {{ inventory_hostname }}"
    - name: Add proxy names
      lineinfile:
        dest: '/etc/environment'
        line: '{{ item }}'
      with_items:
        - 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
        - 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
        - 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - name: Install Apache
      apt:
        name: ['apache2']
        update_cache: yes
        state: latest