availability_zone: melbourne-qh2-uom

volumes:
  - vol_name: helloWorldVol
    vol_size: 6
# -  vol_name: anotherVolume
#    vol_size: 10

security_groups:
  - name: demo_ssh
    description: "Add description here"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0 # TODO: fix debug; 128.250.0.0/16 # only ip addresses from unimelb
  - name: demo_couchdb
    description: "Gives access to Fauxton"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0


instance_image: 0c02a3c6-3465-47cf-a495-7d87975260b0 # Ubuntu 18.10
instance_key_name: andy # TODO: change this
instance_flavor: uom.mse.2c9g 
instance_name: helloWorld
