availability_zone: melbourne-qh2-uom

volumes:
  manager_Vol:
    size: 10
  work1_Vol:
    size: 10
  work2_Vol:
    size: 10
  work3_Vol:
    size: 10

security_groups:
  - name: demo_ssh
    description: "Allows SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0 # TODO: fix debug; 128.250.0.0/16 # only ip addresses from unimelb
  - name: demo_couchdb
    description: "Gives access to Fauxton"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0


instance_image: 0c02a3c6-3465-47cf-a495-7d87975260b0 # Ubuntu 18.10
instance_key_name: andy # TODO: change this
instance_flavor: uom.mse.2c9g

instances:
  - name: manager
    group: managers
    volumes: ['manager_Vol']
  - name: worker_1
    group: workers
    volumes: ['work1_Vol']
  - name: worker_2
    group: workers
    volumes: ['work2_Vol']
  - name: worker_3
    group: workers
    volumes: ['work3_Vol']

instance_name: testXYZ # TODO: Remove this; kept to make script work


