#
# For Cloud Team 63:
#  * Akshaya Shankar - 1058281
#  * Andy Phan - 696382
#  * Chenbang Huang - 967186
#  * Prashanth Shrinivasan - 986472
#  * Qian Sun – 1027266
#

FROM nginx:alpine

COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf